### ISSUE TITLE
PyVCF dependency on setuptools>=58 causing installation error

### ISSUE THREAD

**Issue by mpiyush21** [dermasugita/Viola-SV#105]
Hi,

Thank you for this package. While trying to install this package in Conda environment with Python 3.9, it appears PyVCF is no longer maintained and it is  causing installation error with following message:

"error in PyVCF setup command: use_2to3 is invalid."

Looking at PyVCF github, this appears to be a problem with setuptools>=58 requirements. 

Please let me know if you have any suggestions.

Cheers
Piyush

**Comment by mpiyush21** [comment]
Further to my message, it appears there is PyVCF3 package. Could this be integrated in the Viola package instead of PyVCF?

**Comment by dermasugita** [comment]
Hi,

Thanks for feedback!
We're currently working on the development of PyVCF-independent VCF reader.
Instead, Viola can be installed by downgrading setuptools to version 57.4.0.

Best regards

**Comment by mpiyush21** [comment]
Thank you. I have downgraded the setuptools to 57.4.0 which successfully helped installing the package. However, this perhaps creates conflict with the latest version of scipy while importing viola in Python 3.9.

**Comment by mpiyush21** [comment]
Here is the error log:

Traceback (most recent call last):

  File "<stdin>", line 1, in <module>

  File
"/g/data3/zc9/users/pm6365/Softwares/anaconda3/lib/python3.9/site-packages/viola/__init__.py",
line 3, in <module>

    from viola.io.api import (

  File
"/g/data3/zc9/users/pm6365/Softwares/anaconda3/lib/python3.9/site-packages/viola/io/api.py",
line 1, in <module>

    from viola.io.parser import (

  File
"/g/data3/zc9/users/pm6365/Softwares/anaconda3/lib/python3.9/site-packages/viola/io/parser.py",
line 14, in <module>

    from viola.core.bedpe import Bedpe

  File
"/g/data3/zc9/users/pm6365/Softwares/anaconda3/lib/python3.9/site-packages/viola/core/bedpe.py",
line 30, in <module>

    from sklearn.cluster import AgglomerativeClustering

  File
"/g/data3/zc9/users/pm6365/Softwares/anaconda3/lib/python3.9/site-packages/sklearn/__init__.py",
line 82, in <module>

    from .base import clone

  File
"/g/data3/zc9/users/pm6365/Softwares/anaconda3/lib/python3.9/site-packages/sklearn/base.py",
line 17, in <module>

    from .utils import _IS_32BIT

  File
"/g/data3/zc9/users/pm6365/Softwares/anaconda3/lib/python3.9/site-packages/sklearn/utils/__init__.py",
line 21, in <module>

    from scipy.sparse import issparse

  File "/g/data/zc9/users/pm6365/Softwares/scipy/__init__.py", line 153, in
<module>

    from scipy._lib._ccallback import LowLevelCallable

  File "/g/data/zc9/users/pm6365/Softwares/scipy/_lib/_ccallback.py", line
1, in <module>

    from . import _ccallback_c

ImportError: cannot import name '_ccallback_c' from 'scipy._lib'
(/g/data/zc9/users/pm6365/Softwares/scipy/_lib/__init__.py)

**Comment by dermasugita** [comment]
Sorry for late reply.

It seems that you are using Anaconda environment that we've not tested. So please try the following first.
- Try `pipenv`/`virtualenv`/`venv` environment instead of Anaconda.
- If you have to use Anaconda environment, try [this](https://stackoverflow.com/questions/46721713/importerror-cannot-import-name-ccallback-c).

If the above does not work, please let us know again.

**Comment by mpiyush21** [comment]
Thanks. I have resolved the issue by creating a separate environment with setuptools v57.4.0 and then uninstalling and reinstalling scipy library.
